### ISSUE TITLE
Need to work with ESP32 Please Help ??

### ISSUE THREAD

**Issue by suyashM6262** [AJMansfield/TriacDimmer#19]
I am trying to do dimmer with TriacDimmerCircuit with internet control... Please Help me... IT help lot for Me... Thank you in advance,,

**Comment by AJMansfield** [comment]
This library is not a cross-platform implementation of triac dimmer control, it's a hardware-specific driver for using hardware acceleration features of Atmel ATMEGA and ATtiny microcontrollers, and can't be used on ESP32.

For an ESP32 compatible library, I'd recommend looking at a cross-platform dimmer library like this one: https://github.com/fabiuz7/Dimmable-Light-Arduino
