### ISSUE TITLE
Please add the test circuit

### ISSUE THREAD

**Issue by YordanYanakiev** [AJMansfield/TriacDimmer#6]
Hello.
Please add the schematic of the test circuit used with this library.

**Comment by AJMansfield** [comment]
Thanks for the feedback, I'll work on adding an illustration.

For the moment the circuit is described in the [basic example](https://github.com/AJMansfield/TriacDimmer/blob/master/examples/basic_example/basic_example.ino#L19-L25):

```
  The circuit:
  * Pin 8 is connected to the dimmer 'sync' pin.
  * Pin 9 is connected to the dimmer 'ch 1' pin.
  * Pin 10 is connected to the dimmer 'ch 2' pin.
  * The dimmer power input is connected to mains AC power.
  * The dimmer channel 1 and channel 2 outputs are connected 
      to lightbulbs or other devices.
```

**Comment by YordanYanakiev** [comment]
Oh. Seems like I've missed this. I'll search for the circuit schematic of the used board now.
Thank You very much AJMansfield !

**Comment by AJMansfield** [comment]
I've added the wiring diagram to the readme.
